-- Role: judge
DROP ROLE IF EXISTS judge;

CREATE ROLE judge WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;
  
  
GRANT SELECT, UPDATE ON TABLE contracts TO judge;
GRANT SELECT, UPDATE ON TABLE subcontracts TO judge;

