-- Role: importer
DROP ROLE IF EXISTS importer;

CREATE ROLE importer WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT SELECT, UPDATE ON TABLE accounts TO importer;
GRANT SELECT, INSERT, UPDATE ON TABLE contracts TO importer;

